---
sidebar: false
toc: false
---


## Introduction to R

| Audience   | Computational skills required | Duration                                                   |
|:---------------------|:---------------------------|:---------------------|
| Biologists | None                          | 4-session online workshop (\~ 8 hours of trainer-led time) |

### Description

This repository has teaching materials for a hands-on **Introduction to R** workshop. The workshop will introduce participants to the basics of R and RStudio. R is a simple programming environment that enables the effective handling of data, while providing excellent graphical support. RStudio is a tool that provides a user-friendly environment for working with R. These materials are intended to provide both basic R programming knowledge and its application for increasing efficiency for data analysis.

**Note for Trainers:** Please note that the schedule linked below assumes that learners will spend between 2-3 hours on reading through, and completing exercises from selected lessons between classes.

### Learning Objectives

1.  **R syntax**: Familiarize the basic syntax and the use of Rstudio.
2.  **Data types and data structures**: Describe frequently-used data types and data structures in R.
3.  **Data inspection and wrangling**: Demonstrate the utilization of functions and indices to inspect and subset data from various data structures.
4.  **Data visualization**: Apply the ggplot2 package to create plots for data visualization.

### Lessons

- [Workshop schedule (trainer-led learning)](schedule/schedule.qmd)
- [Self-learning](schedule/links-to-lessons.qmd)

### Installation Requirements

Download the most recent versions of R and RStudio for the appropriate OS using the links below:

-   [R](https://cran.r-project.org/)
-   [RStudio](https://www.rstudio.com/products/rstudio/download/#download)

### Dataset

All the files used for the above lessons are linked within, but can also be [accessed here](https://www.dropbox.com/scl/fi/yszqm3ri6p4uf5ppuflp1/data.zip?rlkey=c496frt1ioud8rrbo9ea1614p&st=fw7fhif8&dl=1).

------------------------------------------------------------------------

### Citation

To cite material from this course in your publications, please use:

::: callout-important
Meeta Mistry, Mary Piper, Jihe Liu, & Radhika Khetani. (2021, May 5). *hbctraining/Intro-to-R-flipped: R workshop first release*. Zenodo. https://doi.org/10.5281/zenodo.4739342. RRID:SCR_025373
:::

A lot of time and effort went into the preparation of these materials. Citations help us understand the needs of the community, gain recognition for our work, and attract further funding to support our teaching activities. Thank you for citing this material if it helped you in your data analysis.
